### ISSUE TITLE
W5500 Ethernet shield intermittent connection lost

### ISSUE THREAD

**Issue by dew1989** [Xinyuan-LilyGO/LilyGo-T-Relay#47]
Having some issues with my S3 relay and w5500 Ethernet shield. The device randomly disconnects over 10 times a day, for anywhere from 3-10 mins then connects again. Ethernet code is as follows
```
ethernet:
   type: W5500
   clk_pin: GPIO10
   mosi_pin: GPIO12
   miso_pin: GPIO11
   cs_pin: GPIO09
   interrupt_pin: GPIO13
   reset_pin: GPIO14
   clock_speed: 25Mhz

   # Optional manual IP
   manual_ip:
     static_ip: 10.0.0.163
     gateway: 10.0.0.1
     subnet: 255.255.255.0
```
